version: '3.8'

services:

    mongo:
        image: mongo:latest
        restart: always
        container_name: mongo-docker
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: mongoadmin
            MONGO_INITDB_DATABASE: demodb
        ports:
            - "27017:27017"
        networks:
            - demo-tester-spring-mongodb

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        ports:
            - "28081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: changeme
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
            ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:27017/ 
        depends_on:
            - mongo
        networks:
            - demo-tester-spring-mongodb

networks:
    demo-tester-spring-mongodb: