version: '3.8'

services:

    mongo0:
        image: mongo:latest
        hostname: mongo0
        container_name: mongo0
        command: >
            mongod
            --replSet rs0
            --bind_ip localhost,mongo0
        ports:
            - 27017:27017
        restart: unless-stopped
        volumes:
            - ./data/db0:/data/db
        networks:
            - demo-tester-spring-mongodb

    mongo1:
        image: mongo:latest
        hostname: mongo1
        container_name: mongo1
        command: >
            mongod
            --replSet rs0
            --bind_ip localhost,mongo1
        ports:
            - 27018:27017
        restart: unless-stopped
        volumes:
            - ./data/db1:/data/db
        networks:
            - demo-tester-spring-mongodb

    mongo2:
        image: mongo:latest
        hostname: mongo2
        container_name: mongo2
        command: >
            mongod
            --replSet rs0
            --bind_ip localhost,mongo2
        ports:
            - 27019:27017
        restart: unless-stopped
        networks:
            - demo-tester-spring-mongodb

    mongo-rs-init:
        image: mongo:latest
        container_name: mongo-rs-init
        depends_on:
            - mongo0
            - mongo1
            - mongo2
        entrypoint: ["replica_set_init.sh"]
        restart: on-failure
        volumes:
            - ./replica_set_init.sh:/usr/local/bin/replica_set_init.sh:ro
        networks:
            - demo-tester-spring-mongodb
            
    mongo-express-01:
        image: "mongo-express:latest"
        container_name: "mongo-express-01"
        restart: always
        ports:
            - "28081:8081"
        networks:
            - demo-tester-spring-mongodb
        depends_on: 
            - "mongo0"
            - "mongo1"
            - "mongo2"
        environment:
            ME_CONFIG_MONGODB_URL: "mongodb://mongo0:27017,mongo1:27017,mongo2:27017/?replicaSet=rs0"

    demospringmongobackend-01:
        image: orbartal/demo-mongo-spring-backend:latest
        hostname: demospringmongobackend
        container_name: demospringmongobackend-01
        depends_on:
            - mongo0
            - mongo1
            - mongo2
        ports:
            - 8080:8080
        environment:
        #MongoDB
            - SPRING_DATA_MONGODB_URI=mongodb://mongo0:27017,mongo1:27017,mongo2:27017/?replicaSet=rs0
            - SPRING_DATA_MONGODB_DATABASE=demodb
            - SPRING_DATA_MONGODB_USERNAME=demouser
            - SPRING_DATA_MONGODB_PASSWORD=demopass
        networks:
            - demo-tester-spring-mongodb

    demospringmongotester-01:
        image: orbartal/demo-mongo-spring-tester:latest
        hostname: demospringmongotester
        container_name: demospringmongotester-01
        depends_on:
            - demospringmongobackend-01
        ports:
            - 8090:8090
        networks:
            - demo-tester-spring-mongodb
        environment:
            - demo.backend.url=http://demospringmongobackend:8080        

networks:
    demo-tester-spring-mongodb: