version: '3.8'

services:

    mongo.one.db:
        image: mongo:latest
        hostname: mongo.one.db
        container_name: mongo.one.db
        restart: always
        volumes:
            - ./data/db1:/data/db    
        networks:
            demo-tester-spring-mongodb-one:
        ports:
            - 20000:27017
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsone" ]

    mongo.two.db:
        image: mongo:latest
        hostname: mongo.two.db
        container_name: mongo.two.db
        restart: always
        volumes:
            - ./data/db2:/data/db
        networks:
            demo-tester-spring-mongodb-one:
        ports:
            - 20001:27017
        depends_on:
            - mongo.one.db
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsone" ]

    mongo.three.db:
        image: mongo:latest
        hostname: mongo.three.db
        container_name: mongo.three.db
        restart: always
        volumes:
            - ./data/db3:/data/db
        networks:
            demo-tester-spring-mongodb-one:
        ports:
            - 20002:27017
        depends_on:
            - mongo.one.db      
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsone" ]

    mongo-express-one:
        image: "mongo-express:latest"
        container_name: "mongo-express-one"
        restart: always
        ports:
          - 8081:8081
        networks:
            demo-tester-spring-mongodb-one:
        depends_on: 
          - mongo.one.db
          - mongo.two.db
          - mongo.three.db
        environment:
            ME_CONFIG_MONGODB_URL: "mongodb://mongo.one.db:27017,mongo.two.db:27017,mongo.three.db:27017/?replicaSet=rsone"

    demospringmongobackend-one:
        image: orbartal/demo-mongo-spring-backend:latest
        hostname: demospringmongobackend
        container_name: demospringmongobackend-one
        restart: always
        depends_on:
          - mongo.one.db
          - mongo.two.db
          - mongo.three.db
        ports:
            - 8080:8080
        environment:
            #MongoDB
            - SPRING_DATA_MONGODB_URI=mongodb://mongo.one.db:27017,mongo.two.db:27017,mongo.three.db:27017/?replicaSet=rsone
            - SPRING_DATA_MONGODB_DATABASE=demodb
            - SPRING_DATA_MONGODB_USERNAME=demouser
            - SPRING_DATA_MONGODB_PASSWORD=demopass
        networks:
            - demo-tester-spring-mongodb-one

    demospringmongotester-one:
        image: orbartal/demo-mongo-spring-tester:latest
        hostname: demospringmongotester
        container_name: demospringmongotester-one
        restart: always
        depends_on:
            - demospringmongobackend-one
        ports:
            - 8090:8090
        networks:
            - demo-tester-spring-mongodb-one
        environment:
            - demo.backend.url=http://demospringmongobackend:8080            

networks:
    demo-tester-spring-mongodb-one:
        driver: bridge